# docker compose nos va a permitir definir
# - servicios
# - redes
# - volumenes y mas...
services:
  usuarios:
    build: ./usuarios # siempre va la carpeta donde esta el dockerfile del servicio
    image: servicio-usuarios:1.0
    container_name: usuarios
    env_file:
      - ./usuarios/.env
    ports:
      - "5000:5000"
    networks:
      - red_microservicios
  pedidos:
    build: ./pedidos
    image: servicio-pedidos:1.0
    container_name: pedidos
    env_file:
      - ./pedidos/.env
    # environment: sobreescribir las variables de entorno de .env
    environment:
      - PORT=5001
      - USUARIOS_HOST=usuarios
      - USUARIOS_PORT=5000
      - DATA_DIR='./data'
      - NODE_ENV=development
    volumes:
      - pedidos-data:/data
    ports:
      - "5001:5001"
    depends_on:
      - usuarios
    networks:
      - red_microservicios
  gateway:
    build: ./gateway
    image: servicio-gateway-educativo:1.0
    container_name: gateway
    env_file:
      - ./gateway/.env
    environment:
      - USUARIOS_URL=http://usuarios:5000
      - PEDIDOS_URL=http://pedidos:5001
      - INVENTARIO_URL=http://inventario:5002
    ports:
      - "8080:8080"
    depends_on:
      - usuarios
      - pedidos
      - inventario
    networks:
      - red_microservicios
  inventario:
    build: ./inventario
    image: servicio-inventario:1.0
    container_name: inventario
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5002
      - DATABASE_URL=Host=postgres;Port=5432;Database=inventario_db;Username=postgres;Password=postgres123
    ports:
      - "5002:5002"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - red_microservicios
    restart: on-failure
  dashboard:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    image: dashboard-microservicios:1.0
    container_name: dashboard
    ports:
      - "3000:80"
    depends_on:
      - gateway
    networks:
      - red_microservicios
  # ! Base de datos PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: postgres_microservicios
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=inventario_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - red_microservicios
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  red_microservicios:
    driver: bridge

volumes:
  pedidos-data:
    driver: local
  postgres-data:
    driver: local
