# Deployment = Gateway
#  El punto de entrada principal
#  se comunica con usuarios y pedidos internamente

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: microservicios-app
  labels:
    app: gateway
spec:
  replicas: 2 # asigna el numero de pods (containers) a ejecutar
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: api-gateway-educativo:1.0
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: NODE_ENV
          value: "production"
        - name: USUARIOS_URL
          value: "http://usuarios:5000"
        - name: PEDIDOS_URL
          value: "http://pedidos:5001"
        resources:
          request: # recursos Minimos garantizados
            memory: "128Mi"
            cpu: "100m"
          limits: # recursos Maximos permitidos
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /pedidos
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /pedidos
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 10
