apiVersion: v1
kind: Service
metadata:
  metadata:
  name: gateway
  namespace: microservicios-app
  labels:
    app: gateway
spec:
  type: NodePort # accesible desde fuera del cluster
  selector:
    app: gateway
  ports:
  - port: 8080 #el puerto interno del servicio
    targetPort: 8080 # puerto del contenedor
    nodePort: 30080 # puerto en el nodo que debe estar entre (30000 al 32767)
    protocol: TCP
    name: http

# Accedemos en http://<IP_DEL_NODO>:30080
# En nuestra maquina local http://localhost:30080
