# los configmaps almacenan configuracion no sensible 
# que puede cambiar entre ambientes

apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: microservicios-app
  labels:
    app: gateway
data:
  NODE_ENV: production
  PEDIDOS_URL: http://pedidos:5001
  PORT: "8080"
  USUARIOS_URL: http://usuarios:5000
  REQUEST_TIMEOUT: "5000"
  LOG_LEVEL: "info"