# Nunca se sube a git
# se debe utilizar .gitignore
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: microservicios-app
  labels:
    app: database
type: Opaque
data:
  DB_HOST: cG9zdGdyZXMuZGF0YWJhc2UubG9jYWw=
  DB_NAME: bWljcm9zZXJ2aWNpb3M=
  DB_PASSWORD: TWlDb250cmFzZcOxYVNlZ3VyYTEyMyE=
  DB_PORT: NTQzMg==
  DB_USER: YWRtaW4=

---
# secret de tipo TLS
apiVersion: v1
kind: Secret
metadata:
  name: tls-certificate
  namespace: microservicios-app
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
