apiVersion: v1
kind: Service
metadata:
  name: inventario
  namespace: microservicios-app
  labels:
    app: inventario
spec:
  type: ClusterIP
  selector:
    app: inventario
  ports:
  - name: http
    port: 5002
    targetPort: 5002
    protocol: TCP

# apiVersion: v1
# kind: Service
# metadata:
#   name: inventario
#   namespace: microservicio-app
#   labels:
#     app: inventario
#     type: nodeport
# spec:
#   type: NodePort
#   selector:
#     app: inventario
#   ports:
#   - name: http
#     port: 5002
#     targetPort: 5002
#     nodePort: 30002
#     protocol: TCP