# Deployment = Usuarios
# Define CÃ³mo debe ejecutarse la app.
# especifica que imagen Docker va a utilizar mi app
# controlar cuantas copias de la app quiero.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios-deployment
  namespace: microservicios-app
  labels:
    app: usuarios
spec:
  replicas: 2 # asigna el numero de pods (containers) a ejecutar
  selector:
    matchLabels:
      app: usuarios
  template:
    metadata:
      labels:
        app: usuarios
    spec:
      containers:
      - name: usuarios
        image: us-central1-docker.pkg.dev/eduteklatam/microservicios-repo/servicio-usuarios:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: PORT
          value: "5000"
        - name: NODE_ENV
          value: "production"
        resources:
          requests: # recursos Minimos garantizados
            memory: "128Mi"
            cpu: "100m"
          limits: # recursos Maximos permitidos
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /usuarios
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /usuarios
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
            
