# Deployment = Gateway
#  El punto de entrada principal
#  se comunica con usuarios y pedidos internamente

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: microservicios-app
  labels:
    app: gateway
spec:
  replicas: 2 # asigna el numero de pods (containers) a ejecutar
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: servicio-gateway-educativo:1.0
        ports:
        - containerPort: 8080
          name: http
        # OPCION 1: inyectar las variables del configmap
        envFrom:
        - configMapRef:
            name: gateway-config
        # OPCION 2: variables especificas
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: gateway-config
              key: PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: gateway-config
              key: NODE_ENV
        - name: USUARIOS_URL
          valueFrom:
            configMapKeyRef:
              name: gateway-config
              key: USUARIOS_URL
        - name: PEDIDOS_URL
          valueFrom:
            configMapKeyRef:
              name: gateway-config
              key: PEDIDOS_URL
        resources:
          requests: # recursos Minimos garantizados
            memory: "128Mi"
            cpu: "100m"
          limits: # recursos Maximos permitidos
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
